//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public long id { get; set; }
        public long flight_id { get; set; }
        public long seat_number { get; set; }
        public long user_id { get; set; }
    
        public virtual flights flights { get; set; }
        public virtual users users { get; set; }
    }
}
