//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flights()
        {
            this.tickets = new HashSet<tickets>();
        }
    
        public long id { get; set; }
        public string flight_name { get; set; }
        public Nullable<long> departure_city { get; set; }
        public Nullable<long> arrival_city { get; set; }
        public long airplane_id { get; set; }
        public System.DateTime departure_date { get; set; }
        public System.TimeSpan travel_time { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public double price { get; set; }
    
        public virtual airplane airplane { get; set; }
        public virtual cities cities { get; set; }
        public virtual cities cities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tickets> tickets { get; set; }
    }
}
