//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class course_work_WPF_EFEntities : DbContext
    {
        public course_work_WPF_EFEntities()
            : base("name=course_work_WPF_EFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airplane> airplane { get; set; }
        public virtual DbSet<archive_flights> archive_flights { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<flights> flights { get; set; }
        public virtual DbSet<system> system { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<users> users { get; set; }
    
        public virtual ObjectResult<GetStatisticsOnSoldTickets_Result> GetStatisticsOnSoldTickets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStatisticsOnSoldTickets_Result>("GetStatisticsOnSoldTickets");
        }
    }
}
