//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class system
    {
        public long user_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public bool is_admin { get; set; }
        public Nullable<long> id_passenger { get; set; }
    }
}
